#define HEXCOLOR(c) [UIColor colorWithRed:((c>>24)&0xFF)/255.0 \
green:((c>>16)&0xFF)/255.0 \
blue:((c>>8)&0xFF)/255.0 \
alpha:((c)&0xFF)/255.0];

//#define TIMER_EVENT_MINUTE @"timerEventMinute"

#define LOCATION_REPORTING_TIME_RANGE_MINUTES 60
#define LOCATION_REPORTING_ADDITIONAL_TIME_WHILE_RUNNING_MINUTES 90
#define FETCH_REPORTED_LOCATIONS_TIME_RANGE_MINUTES 180
#define CHECKIN_RADIUS_THRESHOLD 60
#define CHECKIN_ACCURACY_THRESHOLD 100
#define STALE_DATA_FETCH_MINUTES_THRESHOLD 5
#define REPORTING_LOCATION_DISTANCE_TRAVELLED_METERS_THRESHOLD 50
#define REPORTING_LOCATION_MINUTES_UNTIL_STALE_THRESHOLD 60
#define DATA_FETCH_TIMEOUT_SECONDS_INTERVAL 12
#define GOOGLE_API_KEY @"AIzaSyAIcJ2O5wb1INKqMQzPDnak6f-Z2pbq1mw"
#define GOOGLE_ANALYTICS_PROPERTY_ID @"UA-24038628-2"
#define GOOGLE_ANALYTICS_DISPATCH_PERIOD 10
#define SIMPLE_GEO_SEARCH_RESULTS_COUNT 35
#define SIMPLE_GEO_CONSUMER_KEY @"bcRryckAyj5YT3ZrSGraENdxqdLJRz9Q"
#define SIMPLE_GEO_CONSUMER_SECRET @"q2AMUDLyHpcPuaKkETchSqxQaPrY2fD9"
#define YELP_SEARCH_RESULTS_COUNT 20
#define YELP_CONSUMER_KEY @"MRgCPmRplDC1JJEmPnTykg"
#define YELP_CONSUMER_SECRET @"	1zZPJCuqmCqBOdCboPEGwLMMICQ="
#define YELP_TOKEN @"DRVA5JDqUagRLV8wmnV7vpIm5qMjwz0q"
#define YELP_TOKEN_SECRET @"wueZ5gAPHSCUjOqdYy-6AdC9U-g"

// User setting keys
#define USER_PREF_ALLOW_TRACKING @"allowsTracking"
#define USER_PREF_ALLOW_CHECKIN @"allowsCheckin"

// App settings keys
#define APP_STORE_ID @"appStoreId"
#define APP_STORE_VERSION @"appStoreVersion"
#define APP_STORE_VERSION_CHECK_FREQUENCY_DAYS 7